### ISSUE TITLE
support `GPT2LMHeadModel`(GPT2 model) sharding

### ISSUE THREAD

**Issue by eagle705** [huggingface/text-generation-inference#1152]
### Feature request

I would like to request the addition of a feature that allows for sharing larger GPT-2(`GPT2LMHeadModel`) models (e.g., 39B, 70B) in the class. Currently, this is not supported, and I'd like to be able to share and use these larger models. Thank you

### Motivation

many researcher also use GPT-2(`GPT2LMHeadModel`) model. 
however, TGI currently do not support it

````
model = get_model(\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py\", line 291, in get_model\n    raise ValueError(\"sharded is not supported for AutoModel\")\nValueError: sharded is not supported for AutoModel\n"},"target":"text_generation_launcher"}

````

### Your contribution

I will try to submit a PR or.. I just check

**Comment by dopc** [comment]
any update on this, I got this error with [that model](https://huggingface.co/AI-Sweden-Models/gpt-sw3-6.7b-v2-instruct).

I have two other issues about this:

1. I got an error (`ValueError: Calling cuda() is not supported for 4-bit or 8-bit quantized models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct dtype.`) when I try using the quantization method for this model.
2. I got another error (`ValueError: gptq quantization is not supported for AutoModel`) when I try to use [gptq-ed version](https://huggingface.co/AI-Sweden-Models/gpt-sw3-6.7b-v2-instruct-4bit-gptq) of the above model.
