### ISSUE TITLE
Docker File: Max Jobs Arg & CVEs

### ISSUE THREAD

**Issue by amzn-choeric** [huggingface/text-generation-inference#1277]
### Feature request

Can we add a MAX_JOBS arg in the Dockerfile and set the environment variable for it if set?

Can we address vulnerabilities CVE-2023-38545 (libcurl4) and CVE-2023-47248 (pyarrow) for the latest versions? More emphasis on the pyarrow issue.

### Motivation

The motivation for the MAX_JOBS args is with regards to building flash-attention-v2. Depending on the machine used (CPUs, memory, etc.), that seems to be a choking point (memory issues) if the parallelization is beyond what the machine can support. 

### Your contribution

I do not think I am allowed to contribute unfortunately.

**Comment by Narsil** [comment]
I don't think pyarrow is actively used by this repo. Seems like an artifact from vllm : https://github.com/vllm-project/vllm/blob/main/requirements.txt

Since they don' t pin the version I think just reinstalling from a more recent version should fix it.

We added MAX_JOBS since the compilation also burst past out of our RAM in our builds: https://github.com/huggingface/text-generation-inference/blob/main/Dockerfile
