### ISSUE TITLE
[BestPractices] Tuning inference server to avoid OOM

### ISSUE THREAD

**Issue by mapa17** [huggingface/text-generation-inference#1323]
Hi,
i would like to avoid the inference server to run OOM because of high load/long requests.

I am currently trying to use `text-generation-benchmark` with different sequence-length and batch-size to estimate maximum capacity of the server, but fail to understand how to adjust the server parameters.

In particular the server parameters:
- `--max-batch-total-tokens`: I am using flash-attention 2 for my model and get a deprecation warning with this option. This means it does not take affect?
- `--cuda-memory-fraction`: is often mentioned, but what does this do? In my case i still run OOM trying to process too long sequences setting the memory fraction to for example 80%.

In particular I am surprised by for example being able to handle with the benchmark tool the configuration 
--sequence-length 4000 -b=1

But will run out of memory when trying
--sequence-length 1000 -b=3

How is this possible?

In addition I noticed that during inference server start I get very strange `Inferred max batch total token` values.
For the settings
`--max-input-length 2048 --max-total-tokens 4000 --max-concurrent-requests 2 --max-batch-total-tokens 4000 --max-batch-prefill_tokens 3000`

The server logs say
`Inferred max batch total tokens: 29888`

Why?

Thank you!

**Comment by Narsil** [comment]
The benchmark tool bypasses the router, which is in charge of preventing OOM.

We might implement something, but the benchmark currently connects directly to the GPUs, and runs exactly what you asked, eventually causing OOMs.

OOMs shouldn't happen in production though, because TGI has a warmup phase where it looks at how much memory is actually used during inference, and caps that memory.

OOM in benchmark: Not a bug (something we might update in the future, but not an immediate worry)
OOM in prod: Bug.
