### ISSUE TITLE
Painless Inference Acceleration

### ISSUE THREAD

**Issue by XianglongTan** [huggingface/text-generation-inference#1432]
### Feature request

Painless Inference Acceleration: https://github.com/alipay/PainlessInferenceAcceleration/issues/new
Use Trie Tree to store guesses and verify multiple guesses at one forward pass. 

### Motivation

The author report a 5x acceleration on RAG scenerio. 

### Your contribution

I am new to the TGI and the Painless Inference Acceleration project. Maybe I can develop some features afther I get familiar with them.

**Comment by Narsil** [comment]
Tree lookahead is prohibitively costly in inference scenarios. We already support speculation ( `--speculate n` or just loading a medusa model) which is just as effective.

Tree based is prohibitive because you incur that much compute on the GPU. And in single user settings that's fine since most model are currently memory bound. However, in a serving settings, having every user consume 10x more compute means you're reaching compute bound almost instantly, meaning that dynamic batching stops being interesting and you're throughput limited much faster.

That's why even speculation is not activated by default (it requires users to make a judgement call on throughput cost VS latency speedup provided by the speculation). Also tree based hits much less often than regular top1 speculation.

**Comment by XianglongTan** [comment]
Thanks for your reply. One more question, if I care more about low latency and the generation quality, what else can I do besides tuning the speculate parameters?

**Comment by XianglongTan** [comment]
Also we have a scenario that needs LLM to generate multiple json format result. And we have verified that the strong LLM can decode different key-value paris correctly in parallel way. Say the dictionary have three keys, strong LLM can generate three corresponding values at the same time and with very little quality loss. I am wondering how to combine this kind of generate method into TGI. Would you please offer some advice?
