### ISSUE TITLE
Medusa's acceleration in doubt & v1.3.3 slowers the inference

### ISSUE THREAD

**Issue by eurus-ch** [huggingface/text-generation-inference#1503]
Running TGI benchmark on A30*4 with speculate(3) and TGI v1.3.3/1.1,1, 13B model: 
<img width="848" alt="未命名" src="https://github.com/huggingface/text-generation-inference/assets/56667768/90b9124f-9434-48ee-bf82-4077f19b2373">

Problems are: 

1. why v1.3.3 is slower

2. Speculative(3) seems to accelerate significantly, but I didn't observe the same result with vLLM benchmark and in real use on the same A30*4. Their results look like Medusa doesn't have that much effect. Are there any potential limits, like memory cost?

   ```
   #non-sp
   Total time: 33.53 s
   Throughput: 2.98 requests/s
   Average latency: 17.67 s
   Average latency per token: 0.03 s
   Average latency per output token: 0.54 s
   
   #sp=3
   Total time: 32.52 s
   Throughput: 3.08 requests/s
   Average latency: 17.54 s
   Average latency per token: 0.03 s
   Average latency per output token: 0.54 s
   ```
Thanks so much for your work!

**Comment by Narsil** [comment]
I don't have a lot of backgrounds on that figure so hard to tell you anything.
How did  you produce it ?

Medusa models will perform highly on how they are finetuned. We are working on making them more ubiquitous: https://github.com/huggingface/text-generation-inference/issues/1493#issuecomment-1919554168

Medusa *will* limit the throughput if the hitrate is too low (which is the case on poorly trained models which is mostly the case with the default recipe unless it' s a vicuna). The reason is that is uses compute to do speculation, which never gets accepted therefore never accelerates the model.
