### ISSUE TITLE
loading fast tokenizer implementation for cached model with `HF_HUB_OFFLINE=1` fails

### ISSUE THREAD

**Issue by sfbemerk** [huggingface/text-generation-inference#2147]
### System Info

TGI version: >=2.0.4 affected,  2.0.1 not affected
model: irrelevant, tested e.g. with llama-3-8b-instruct.
hardware: 1x NVIDIA H100

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Download model, e.g. with `huggingface-cli download meta-llama/Meta-Llama-3-8B-Instruct`
2. Start TGI container v2.1.0 with `HF_HUB_OFFLINE=1` and `--model-id "meta-llama/Meta-Llama-3-8B-Instruct"`
3. Observe that TGI starts with warnings 
```
Could not find a fast tokenizer implementation for meta-llama/Meta-Llama-3-8B-Instruct
```
and also, requests at /v1/chat/completions fail with `template not found`, although a chat template is present in the downloaded tokenizer_config.json. 

In contrast, if I explicitly link to the cached model and start the TGI container v.2.1.0 with `HF_HUB_OFFLINE=1` and `--model-id "/path/to/cache/huggingface/hub/models--meta-llama--Meta-Llama-3-8B-Instruct/snapshots/<sha>/"`, the startup works fine without that warning. Also, if I start with `HF_HUB_OFFLINE=0` and provide an authentication token, startup works well, too. 

This bug did not appear in TGI v2.0.1. I haven't tested thoroughly, but I believe this bug already appeared in TGI v2.0.4

### Expected behavior

In my understanding, downloading the model with huggingface-cli and starting with `HF_HUB_OFFLINE=1` should always work without problems. In particular, it should be possible to start TGI with a cached model and still use fast tokenizer implementation.

**Comment by LysandreJik** [comment]
cc @ErikKaum this is likely a request that should be protected by the check whether we're offline or not

**Comment by ErikKaum** [comment]
Thanks for reporting this @sfbemerk 🚀

Yeah I think you're correct, this was probably introduced in release 2.0.2 when support for the `HF_HUB_OFFLINE` variable was added to the router.

PR #2226 should fix this 👍

In the meantime, if you want it to run now. I was able to get it working with this hack:

```bash
docker run -it --gpus all --shm-size 1g -p 8080:80 \
    -e HF_HUB_OFFLINE=1 \
    -v $PWD/data:/data \
    -v $PWD/data:/root/.cache/huggingface/hub \
    ghcr.io/huggingface/text-generation-inference:2.1.1 --model-id "meta-llama/Meta-Llama-3-8B-Instruct"
```

So this assumes that you have the model downloaded in a directory called `data`
- map `data` to `/data` --> model weights are found correctly
- map `data` to `/root/.cache/huggingface/hub` --> tokenizer is found correctly

It's not an ideal way to do it of course and is only for the intermittent time before the fix is released 😅👍
