### ISSUE TITLE
Support for Assisted Generation

### ISSUE THREAD

**Issue by sujithjoseph** [huggingface/text-generation-inference#314]
### Feature request

Can this API support Assisted Generation feature from https://huggingface.co/blog/assisted-generation?

### Motivation

Better Latency.

### Your contribution

Yes..

**Comment by danielkorat** [comment]
Hi @gante 
It would be highly useful to have this feature in TGI.
WDYT?

**Comment by gante** [comment]
@danielkorat 👋 

@Narsil is the specialist in speculation techniques in TGI, including ngram speculation and medusa. It is my impression assisted generation/speculative decoding is not on TGI's plans for now, with the focus going towards medusa-like techniques because they have a higher potential, correct?

**Comment by lp-noel** [comment]
Can we have an update on this please?

**Comment by danielkorat** [comment]
@gante FYI

**Comment by gante** [comment]
I can't speak on behalf of the TGI team, but it is my impression KV cache stuff (e.g. prefix chunking) and model coverage (multimodal models) have a higher priority atm.

Bear with the TGI team, a lot of things are being requested 🙏
