### ISSUE TITLE
Split Large model into multiple gpus

### ISSUE THREAD

**Issue by MohamedAliRashad** [huggingface/text-generation-inference#339]
### Feature request

I have a large model (16B) that i want to split it on two RTX 3090 because only one won't cut it.
How to do so ?

### Motivation

To be able to load the model

### Your contribution

I don't think i will be able to help

**Comment by OlivierDehaene** [comment]
What type of architecture is it?

**Comment by MohamedAliRashad** [comment]
@OlivierDehaene It's `HuggingFaceH4/starchat-alpha`

**Comment by OlivierDehaene** [comment]
`--num-shard 2`

**Comment by MohamedAliRashad** [comment]
@OlivierDehaene How to load the model into `torch.bfloat16` (how can i send this to the docker container run command ?)?

**Comment by OlivierDehaene** [comment]
The model is already loaded in fp16.

**Comment by MohamedAliRashad** [comment]
@OlivierDehaene I don't think so, I get to load the normal way and it gets loaded on the two gpus but using the docker command it gives me an OOM error

**Comment by hrushikesh198** [comment]
Hi @OlivierDehaene , I have the same question, How can I load a 40GB model by splitting it into 2 GPUs, since Model size is larger than my individual GPU memory?
To add some more details, I want to load `TheBloke/Llama-2-70B-GPTQ` into 2xNvidia L4 GPUs each with 24 GB memory.
@MohamedAliRashad Please chime in if you found any efficient Text Generation set up for the above usecase.

Thank you!
