### ISSUE TITLE
TransformerEngine FP8 speedup

### ISSUE THREAD

**Issue by SinanAkkoyun** [huggingface/text-generation-inference#374]
### Feature request

Please help me implementing the speedup generated by using the TransformerEngine of the hopper H100 GPUs

https://github.com/NVIDIA/TransformerEngine
https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/index.html

### Motivation

Inference speedup

### Your contribution

I am working on bringing TE support to lit-llama. However, as this is difficult for me, I am very willing to work on a PR once a solid base is there.

Thank you very much for helping!

**Comment by Narsil** [comment]
Hi @SinanAkkoyun ,

Whenever we get our hands on some H100 and can debug code for it, we will likely implement.

**Comment by SinanAkkoyun** [comment]
Hi @Narsil 
Thank you very much for the reply 😊 
There are actually H100 instances available on Lambda Cloud GPU for $2.40/h

I would be very open to help and also cover some cloud GPU costs if you'd like that

**Comment by Narsil** [comment]
Thanks for the proposal, it's very kind. We don't need the financial support though. Cheers.

**Comment by stefanobranco** [comment]
Has there been any development on this? From what I understand FP8 support is still quite limited in TGI (the docs mention this is not the fastest due to unpacking and padding). Am I correct in understanding that this would replace the current FP8 implementation, or would it be parallel to it?

If this is currently low priority otherwise I think I could come up with a draft PR, though I'll admit I'm also a bit out of my depth here. The accelerate implementation would probably a good point of reference in that case?
