### ISSUE TITLE
GPU with CUDA is capability 7 0 is not supported

### ISSUE THREAD

**Issue by YuantianGao** [huggingface/text-generation-inference#398]
Hi, When I docker run a container, its something wrong with

` GPU with CUDA is capability 7 0 is not supported`

， If it is a problem if my system's cuda is 11.7 and container's cuda is 11.8?

**Comment by YuantianGao** [comment]
> Your GPU is too old to use flash attention accelerated models. You can still use the other models.

Sorry, My GPU is Tesla V100. Is it too old? And my cuda is 12.0

**Comment by Narsil** [comment]
YEs V100 are not supported by flash attention. TGI will default back to non flash versions, which are slower.

**Comment by CarloNicolini** [comment]
How much is expected the token generation to slow down without **FlashAttention**? I am using `tiiuae/falcon-7b-instruct` on a V100 16GB. Just to have an idea in case of upgrade of the GPU.

**Comment by Narsil** [comment]
Very hard to say. It depends on sooo many things.

The biggest downside though, is that without flash, we required padding (adding 0 into requests to get `(Batch_size, longest_seq_len, ...)` tensors).
When you are running many different requests at the same time it's likely 1 request is 2k tokens long ,while 9 others are like 100 tokens long.
In that scenario you'd be runnning 2k x 10 = 20k tokens instead of the 2k + 9 x 100 you could with flash.

That means MUCH more VRAM usage, and much slower inference.

How much slower? It will depend on how often this occurs, how compute bound you are etc... In the deployments we have it has a very signifcant impact to the point where we barely consider non flash models. (It's unavoidable for Alibi models like bloom or MPT as flash doesn't support alibi as of now).
