### ISSUE TITLE
Contribution: helm chart to deploy on GCP Kubernetes

### ISSUE THREAD

**Issue by louis030195** [huggingface/text-generation-inference#503]
was playing around deploying models on GCP and while I wanted to avoid k8s as much as possible it ended up being the simplest solution to me so I put together my effort into this:

https://github.com/louis030195/text-generation-inference-helm

anywhere you would want a link to this?

**Comment by Narsil** [comment]
Here is fine for now.
We're stopping at the docker level reason here, because there are MANY ways to deploy in addition to helm, and we don't want to manage this complexity.

If more community members feel like contributing we might do something more.

I am closing this, but this is still discoverable through search and we can comment on it.

**Comment by SCE-sotoodaa** [comment]
Would like to +1 this, I've had great success running this repo on Docker and was interested in learning what others are doing to scale beyond a single container.

@Narsil I'd be happy to contribute toward a k8s implementation.
