### ISSUE TITLE
How to enable vllm

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/text-generation-inference#536]
### Feature request

How to enable vllm

### Motivation

How to enable vllm

### Your contribution

How to enable vllm

**Comment by OlivierDehaene** [comment]
Use 0.9 and a supported model

**Comment by lucasjinreal** [comment]
@OlivierDehaene Hi, don't if you are stuff in huggingface,
but PLEASE indicates more details not just type use 0.9

1. Does it enabled by default?
2. if not, how to enable?
3. any documentations indicates how to use?

**Comment by Narsil** [comment]
> can be so impatient to github community member.

Please read your initial "Feature request" and tell me you did the effort to actually express intelligibly a feature request ?
Is this a bug ?

There are many ways you could have phrased that, starting with a request to improve the docs because you couldn't find what you want.

Our effort in replies scale with your effort.

1. Yes
3. It's always on ,there's no opt-out, it's just better overall that what was there previously.

There's no doc for it because well, it's not necessary, if you use flash models, you just get it.

It's also NOT vllm. It's a custom variant of PagedAttention, which is what makes vllm faster. We do reuse a slightly modified version of their low level kernel.

**Comment by lucasjinreal** [comment]
@Narsil Hi, where does PagedAttention custom kernel included in?
