### ISSUE TITLE
GPTQ Formats that work (and don't)

### ISSUE THREAD

**Issue by ssmi153** [huggingface/text-generation-inference#601]
Now that we can load GPTQ files that haven't been quantized by TGI's quantization script, I thought I'd do a set of tests to see which formats work and which don't. I'm using https://huggingface.co/TheBloke/OpenOrca-Preview1-13B-GPTQ as an example set.

1) The 'most compatible' format ([main] branch) doesn't work. This throws the following error: `RuntimeError: weight model.layers.0.self_attn.q_proj.g_idx does not exist`
2) Fortunately, the other formats provided by TheBloke do seem to work. In particular: `gptq-4bit-128g-actorder_True` definitely loads correctly. To use this, you need to set the following environment variables: `GPTQ_BITS = 4`, `GPTQ_GROUPSIZE = 128`  (matching the groupsize of the quantized model). Additionally, you need to pass in `REVISION = gptq-4bit-128g-actorder_True` to pull the correct version of this model (rather than the default version which still doesn't work).

So overall this is great news - we can now load GPTQ files that other people have converted rather than relying on the inbuilt quantizer in TGI!

**Comment by TheBloke** [comment]
That's great to hear.  I started adding those extra quant formats recently with software like TGI and ExLlama in mind.

To the developers of the GPTQ plugin I'd like to ask: is there any chance you could add support for the `quantize_config.json` file?  It's produced automatically by AutoGPTQ when making a quantisation, and I provide it with every one of my GPTQ files, even the ones made with GPTQ-for-LLaMa.  It contains all the GPTQ parameters, and it could easily be used as a source for the GPTQ params, saving the user the need to set them manually via env vars.

Here's an example `quantize_config.json`:

```json
{
  "bits": 4,
  "group_size": 128,
  "damp_percent": 0.01,
  "desc_act": true,
  "sym": true,
  "true_sequential": true,
  "model_name_or_path": null,
  "model_file_base_name": null
}
```

Pretty self explanatory. You'd just need to read `bits` and `group_size` from this file, found in the model folder, and it could work automatically.

I'd be happy to PR a change myself, if someone confirms it would be merged.

**Comment by kaleko** [comment]
Similar issue for me, trying to get Vicuna 7B GPTQ models to run with TGI
`RuntimeError: weight model.layers.0.self_attn.q_proj.weight does not exist`

So far haven't gotten it to work. Looking forward to the README updates with more info about using these models with TGI @TheBloke !

**Comment by TheBloke** [comment]
@kaleko I updated the Vicuna 7B v1.3 GPTQs yesterday.  Download one of the models from the other branches, as listed under Provided Files.  They will work if you manually set the GPTQ_BITS and GPTQ_GROUPSIZE as ssmi153 mentioned in the first post.

You can download from alternate branches using the `REVISION` parameter in TGI.

https://huggingface.co/TheBloke/vicuna-7B-v1.3-GPTQ

**Comment by Narsil** [comment]
> is there any chance you could add support for the quantize_config.json file?

This is actually much cleaner than the ENV variables I added. I'm more than happy to switch to it.
Is it correct to assume that for inference we can discard all other config other than `bits` and `groupsize` ?
Just want to avoid loading/running a model and output garbage if we can raise an error early.

I'm actually very fine aligning and outputting such a config instead of putting the values in the weights. Wdyt @OlivierDehaene  ?

We also have some work to use a better GPTQ kernel: https://github.com/huggingface/text-generation-inference/pull/553 if that's interesting.


The reason for missing `g_idx` is the use of autogpt, correct ?

**Comment by ssmi153** [comment]
The AutoGPTQ quants from TheBloke seem to work actually. It's the ones that TheBloke is converting using GPTQ-for-Llama that are causing the missing `g_idx` error. Weirdly though, the GPTQ model file that I've created using GPTQ-for-Llama loads correctly, so there must be a difference somewhere in the way TheBloke is processing those files, or in the settings he's chosen for them.

@TheBloke , out of interest, how do your GPTQ-for_Llama conversion settings compare to this?:
`%run -i 'GPTQ-for-LLaMa/llama.py' {INPUT_MODEL_FULL_NAME} wikitext2 --wbits 4 --true-sequential --act-order --groupsize 128 --save_safetensors {OUTPUT_MODEL_FULL_NAME_SAFETENSORS}`
My conversion of a 33B Llama model with these settings works with the current TGI implementation. Maybe we can identify any different settings on your side which might allow us to isolate where the problem is.

**Comment by TheBloke** [comment]
My settings are effectively identical.  The reason that my GPTQ-for-LLaMA quants aren't working is that they're using the "old" GPTQ format. There's never been any official GPTQ version naming, but some implementations call it "v1", versus the current "v2" format which has `g_idx`.

AutoGPTQ produces the new format and can load either format, but TGI uses an implementation that can only load the newer v2 format.  It's a shame that TGI chose an implementation that can't load the old format, as it meant that at that time it couldn't support most of the GPTQs on Huggingface.

Going forward I will always be making multiple GPTQs available, nearly all of which will be made with AutoGPTQ and will work.  For now I am still also providing an old GPTQ-for-LLaMa produced version which doesn't work.  I haven't decided yet if if I will continue making that old format version as well - I  need to take a survey of the current state of all the various UIs out there and confirm they can all load the v2 format.

I wanted to switch to making all quants with AutoGPTQ a while back, but as soon as I did I got complaints from users using KobaldAI that the newer format models didn't work with CPU offload.  So to avoid hassle (and because I lacked the time to test it on KoboldAI myself), I just went back to GPTQ-for-LLaMA for making Llama GPTQs.

That issue may even be fixed now, so I should re-evaluate that and hope to do so soon.

Over the last few days I've uploaded multiple options of AutoGPTQ-produced quants to 62 GPTQ repos. And all my non-Llama models (Falcon, MPT, Bloom, Starcoder) were already produced with AutoGPTQ, so should already be TGI compatible. Most of the repos I haven't done are ones I don't plan to do, because they're old and superseded. Eg I didn't do Vicuna v1.1, just v1.3.

My next step is to update my SuperHOT GPTQ repos also - that should happen this weekend.

**Comment by TheBloke** [comment]
> > is there any chance you could add support for the quantize_config.json file?
> 
> This is actually much cleaner than the ENV variables I added. I'm more than happy to switch to it. Is it correct to assume that for inference we can discard all other config other than `bits` and `groupsize` ? Just want to avoid loading/running a model and output garbage if we can raise an error early.

Fantastic, thanks!

The other parameter that sometimes matters is `desc_act`, which in GPTQ-for-LLaMa is called Act Order.   With AutoGPTQ it needs to know whether that's true or false else inference will produce gibberish.

But as you don't have an ENV var for it, I assume that GPTQ-for-LLaMa is able to auto detect that somehow, so it presumably isn't required.  It isn't required in ExLlama so that's further confirmation that it is possible to auto detect it.

> I'm actually very fine aligning and outputting such a config instead of putting the values in the weights. Wdyt @OlivierDehaene ? (If we can reduce the current split around GPTQ it's all for the best)
> 
> We also have some work to use a better GPTQ kernel: #553 if that's interesting.
> 
> The reason for missing `g_idx` is the use of autogpt, correct ?

Sorry I missed your earlier reply when I replied to ssmi's ping, else I'd have replied to you directly, but this is answered above: AutoGPTQ outputs g_idx and the files work fine, it's the old GPTQ-for-LLaMa CUDA version I have been using that doesn't output `g_idx`.

I would really love to stop using that old GPTQ-for-LLaMa code and will do as soon as I've confirmed there's no need to do so any more.

But either way, I'll always have AutoGPTQ-produced GPTQs in future which it's confirmed TGI can load OK.

**Comment by Narsil** [comment]
> I would really love to stop using that old GPTQ-for-LLaMa code and will do as soon as I've confirmed there's no need to do so any more.

You mean using https://github.com/PanQiWei/AutoGPTQ instead of https://github.com/qwopqwop200/GPTQ-for-LLaMa correct ? 
I used specifically https://github.com/qwopqwop200/GPTQ-for-LLaMa because I found the code easier to reason about.

Notably we don't need the modeling code at all in either lib.
I was able to refactor the code to load nothing on the CPU by default, and pull only layer per layer (on CUDA, but could be CPU) for quantization.
Makes everything a bit easier to work with. We currently don't provide a way to select the data sent during quantization but I'm not sure how much that really matter (Didn't seem to matter that much for llama derived models)

All that to say that I'm hesitant to pull from either codebase because they are quite large and we only use a very tiny fraction of the code. Trying to find common grounds would be nice.

**Comment by OlivierDehaene** [comment]
@TheBloke, TGI seems to have issues with H100s I'm not sure why yet.
 Any chance you could test on another device? I was able to launch the model on 1xA10 for example.
 
 You can also use ghcr.io/huggingface/text-generation-inference:sha-44acf72  with the env var `LOG_LEVEL=info,text_generation_launcher=debug` for more logs.

**Comment by TheBloke** [comment]
@Narsil  Sorry, I didn't mean *you* should stop using GPTQ-for-LLaMa.  I was just talking about my own quantising processes. I meant I would like to stop using the old CUDA fork of GPTQ-for-LLaMa for making new quants and uploading them to HF.

I have used an old CUDA fork because for a long time for my 'main' branch GPTQs because there were UIs out there that couldn't support the g_idx GPTQ format in all scenarios.  But that might not be the case any more and I plan to check that.

If you don't even use the modelling code then it sounds like you have a very lightweight implementation so that's great.

@OlivierDehaene  Ah I see, OK thank you.  I wanted to use the H100 specifically as I'm benchmarking TGI vs vLLM and seeing what the max performance I can get in a multi-request scenario on a single GPU.

I tried the logging container but unfortunately I get no extra logs around the crash:
```
2023-07-17T20:15:20.153880Z  WARN text_generation_launcher: We're not using custom kernels.
2023-07-17T20:15:26.260462Z  INFO text_generation_launcher: Server started at unix:///tmp/text-generation-server-0
2023-07-17T20:15:26.267192Z  INFO shard-manager: text_generation_launcher: Shard 0 ready in 9.516731042s rank=0
2023-07-17T20:15:26.363369Z  INFO text_generation_launcher: Starting Webserver
2023-07-17T20:15:27.692885Z  INFO text_generation_router: router/src/main.rs:346: Serving revision 738964d963bd0aa13be29cb3ded3590a803b3b7e of model TheBloke/vicuna-13b-v1.3.0-GPTQ
2023-07-17T20:15:27.701918Z  INFO text_generation_router: router/src/main.rs:212: Warming up model
2023-07-17T20:15:28.912342Z ERROR warmup{max_input_length=1024 max_prefill_tokens=4096 max_total_tokens=16000}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: transport error
Error: Warmup(Generation("transport error"))
2023-07-17T20:15:28.969656Z ERROR text_generation_launcher: Webserver Crashed
2023-07-17T20:15:28.969692Z  INFO text_generation_launcher: Shutting down shards
2023-07-17T20:15:28.994843Z  INFO shard-manager: text_generation_launcher: Shard 0 terminated rank=0
```

Later I'll see if a local install, or a custom Docker container with later pytorch version, makes any difference.

**Comment by TheBloke** [comment]
Ah I just realised it's already reported here: https://github.com/huggingface/text-generation-inference/issues/613 . I'll post there and stop de-railing this thread as it's obviously H100 specific.

**Comment by ssmi153** [comment]
@TheBloke - I just did some benchmarking of TGI on Runpod instances using a range of GPU combinations. (https://docs.google.com/spreadsheets/d/1Ph_GeybAtNVoTs7w4mkCfd7p1lGywsNhJf9z-8fTcUE/edit?usp=sharing - if you're interested). This benchmarking was designed to reflect how I would use TGI and may not be as robust as some of the more formal benchmarks. One thing to note when benchmarking using the Docker image is that I get (and also you look like you've got) a warning saying `WARN shard-manager: text_generation_launcher: We're not using custom kernels.` . I think this is because by default the combination of Runpod + the docker image doesn't have NVIDIA NVCC installed (it requires the developer version of the NVIDIA container toolkit rather than the standard one), so it can't build the custom kernels or vLLM for PagedAttention. I'm struggling to work out whether this warning is a red herring or not, as TGI is still impressively fast. If it is indeed correct, then there should be a further uplift in performance above and beyond what I've seen so far. I haven't yet created an issue about the warning because it felt like I was raising a million Runpod related issues, but if other people are also seeing this (and on other platforms using the Docker image) then it might be worth exploring it further.

**Comment by OlivierDehaene** [comment]
@ssmi153, this warning is a bit dismissive. If you don't see import errors and your architecture is one of the optimized architecture (as displayed in the README), you are using flash and paged attention.
This warning only applies to BLOOM and non-flash neox.

**Comment by bloodsucker99** [comment]
@ssmi153 Can you confirm the new llama 2 gptq versions working? I am getting error with Bloke's autogptq branch:
RuntimeError: weight model.layers.0.self_attn.q_proj.weight does not exist

WizardCoder is also giving an error when trying to load gptq version of it.:

raise RuntimeError(f"weight {tensor_name} does not exist")
RuntimeError: weight gptq_bits does not exist

I am running the docker command with the variables you mentioned at start and there are models that do work so wondering why this one is throwing error as it works fine in fp16.

**Comment by bloodsucker99** [comment]
The fix seems to work for llama 70b but is pretty slow. 

Was wondering if you got the time to check wizardcoder. Still having the issues of loading the gptq version:

raise RuntimeError(f"weight {tensor_name} does not exist")
RuntimeError: weight gptq_bits does not exist

**Comment by fxmarty** [comment]
@bloodsucker99 You need to pass the environment variable `GPTQ_BITS` (though I think gptq_bits and gptq_groupsize could be directly inferred from the shapes of `qweights`, `qzeros`, `g_idx`?)

**Comment by TheBloke** [comment]
Narsil was also looking into adding automatic support for `quantize_config.json` which would provide the bits and group_size without the user needing to specify any env vars.  

But yeah, I think ExLlama can automatically detect quantise config, so maybe neither env vars nor quantize_config.json are needed and it can just be auto detected?  That would be the ideal scenario.

**Comment by keelezibel** [comment]
@TheBloke I am trying to run your quantized model: `TheBloke/Llama-2-70B-chat-GPTQ` on V100 but TGI is complaining about compute capability < 7.5 detected. Is it that flash attn is not supported for V100 GPU? Does that mean all GPTQ models can only run on Ampere or later cards as well?

**Comment by Narsil** [comment]
Indeed flash isn't supported on V100, and sharding requires flash for llama.

**Comment by keelezibel** [comment]
> Indeed flash isn't supported on V100, and sharding requires flash for llama.

I tried to set env var for Sharding to False. But it doesn’t work too. Means I definitely have to load full model on v100 only? I rmb I tried bitsandbytes and it worked but was relatively slower since there is offloading to ram.

**Comment by keelezibel** [comment]
> > older models?
> 
> what do you mean ? All TheBlock models have this quantization configuration, no ?

Sorry i meant older GPU cards such as V100.

**Comment by bloodsucker99** [comment]
So the problem is in flash santacoder modeling, its trying to use to bits values from the weights and not using environment values. Manually forced the use if env variables fixed the issue :)

**Comment by taoari** [comment]
@TheBloke When I tried to run with `TheBloke/Llama-2-7b-Chat-GPTQ`, I got the following error:

warmup{max_input_length=4096 max_prefill_tokens=4096}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
Error: Warmup(Generation("Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`"))

Actually, I am able to serve the official `meta-llama/Llama-2-7b-chat-hf` with `--quantize bitsandtyes` on single T4 GPU. When I change the model to `TheBloke/Llama-2-7b-Chat-GPTQ` with `--quantize gptq`. I got NOT enough memory error. Even when I changed --max-batch-prefill-tokens=2048, this error still happens. Since the bitsandtypes-quantized version can be served on single T4 GPU, gptq-quantized version should be of no problem, do you happen to know why?

**Comment by AIApprentice101** [comment]
I have the same error when trying to load `TheBloke/Llama-2-7b-Chat-GPTQ`

**Comment by samos123** [comment]
I'm hitting the same issue as @taori when trying llama 2 70b chat. The error message:
```yaml
"level":"ERROR","message":"Server error: Not enough memory to handle 4096 prefill tokens. You need to decrease `--max-batch-prefill-tokens`","target":"text_generation_client","filename":"router/client/src/lib.rs","line_number":33,"span":{"name":"warmup"},"spans":[{"max_input_length":1024,"max_prefill_tokens":4096,"name":"warmup"},{"name":"warmup"}]}
```

This is my YAML manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
      - name: llm
        image: ghcr.io/huggingface/text-generation-inference:1.0.3
        resources:
          limits:
            nvidia.com/gpu: 2
        env:
        - name: MODEL_ID
          value: TheBloke/Llama-2-70B-chat-GPTQ
        - name: NUM_SHARD
          value: "2"
        - name: QUANTIZE
          value: gptq
        - name: GPTQ_BITS
          value: "4"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
```
