### ISSUE TITLE
Wrong Variable Name in README

### ISSUE THREAD

**Issue by JacobFidorra** [huggingface/text-generation-inference#638]
The environment variable name in the CUDA Kernels section of the README appears to be wrong.

> CUDA Kernels
The custom CUDA kernels are only tested on NVIDIA A100s. If you have any installation or runtime issues, you can remove the kernels by using the BUILD_EXTENSIONS=False environment variable.

Instead of ``BUILD_EXTENSIONS=False`` you must use ``DISABLE_CUSTOM_KERNELS=True``.
For me this was the solution to my problem. If you agree please change the README accordingly.

**Comment by Narsil** [comment]
They mean different things.

BUILD_EXTENSIONS is a build time flag to say if you want to build the cuda kernels or not
DISABLE_CUSTOM_KERNELS is a runtime flag to prevent using them at runtime (whether they are built or not).

I think we could swap in the README (since for `docker` users it ś already prebuilt, which is likely to be the issue you had).
@OlivierDehaene Do you agree?

**Comment by JacobFidorra** [comment]
Nice! Glad I could make even a minor contribution! Thanks for your work, it helped me a lot!!
I'll close this issue since there is already a merge request.
