### ISSUE TITLE
Flash-attn model taking up all available GPU space.

### ISSUE THREAD

**Issue by rishu931997** [huggingface/text-generation-inference#673]
On the latest version (v0.9.3) when running a flash-attn model (Llama-2-7b-hf), after the model is loaded in the GPU, `max-batch-total-tokens` is being calculated and all of the remaining GPU space is being allocated. I'm not able to set it manually using the `--max-batch-toatl-tokens`. It's saying `--max-batch-total-tokens is deprecated for Flash Attention models.` and then goes on to set it automatically.

I'm running the model on 2xA100 80GB GPU. The model should not be taking more than 20GB of GPU.

Command used: `text-generation-launcher --model-id /models/llama/Llama-2-7b-hf --port 8080 --num-shard 2`

![image](https://github.com/huggingface/text-generation-inference/assets/15365671/ad8942f6-d2cc-48f7-8131-cfcab36c67e9)

![image](https://github.com/huggingface/text-generation-inference/assets/15365671/5d4490f8-a148-4bf4-b01a-3dd1153ef01f)

Is this the expected behavior? This issue was not observed in v0.8.0. Can anyone help me with any setting that I might be missing?

**Comment by michaelfeil** [comment]
Trying to point in a possible direction - there is PagedAttention, which by buffering in the remaining vram achieves some speedup, somewhat proportional to the cache. https://vllm.ai/ Not sure about implementation details on TGI..

**Comment by OlivierDehaene** [comment]
2xA100 80GB is a bit overkill for a 7B don't you think?
That's the normal behaviour for latest. We use all the remaining VRAM for the KV cache. In the past this allocation was not explicit.

**Comment by bloodsucker99** [comment]
@OlivierDehaene This was done very recently right? Recent as in when you added auto max tokens because ever since that, the issue of memory increasing has come back. I am unable to use the builds onward including that commit fe80f5360ca885af4c63a3f1db9f6786df7ebc76 due to the models taking so much ram after the warmup period and then memory starts increasing again with each input. https://github.com/huggingface/text-generation-inference/issues/610 This is the issue im having again after that commit. The model loads fine but once it does warmup, a model that right now sits at 40gb is sitting at ~72gb at start and then increases after the queries are issued and eventually crashing the server. Before that commit, I am running a 13b + 15b (gptq) + stable diffusion all on same system and sitting at ~72gb all together and the queries do not increase the ram as they are flushing properly after the fix you added in the server file.

Could you please look into this.

**Comment by bloodsucker99** [comment]
@OlivierDehaene Can confirm the issue is exactly in that commit because i skipped that commit and cherry-picked all the other commit and built the image locally and all works great but that commit ruins the whole memory stuff so will be skipping on auto max batch tokens ig. Not too big of a deal to me but ye

**Comment by rishu931997** [comment]
> 2xA100 80GB is a bit overkill for a 7B don't you think?
> That's the normal behaviour for latest. We use all the remaining VRAM for the KV cache. In the past this allocation was not explicit.

Yes I used 7b as an example. Before this change I was able to run Falcon-40B and MPT-30B models together in the same system. But now after loading falcon-40B there's no space left for loading MPT-30B as well. Can there be a configuration where we can mention how much of the free GPU it can take after loading the model?

**Comment by OlivierDehaene** [comment]
#659 add `--cuda-memory-fraction` to allow you to limit the amount of memory used by TGI. Let me know if you face any issue with it.
