### ISSUE TITLE
llama2-70b on two a100 (80GB)?

### ISSUE THREAD

**Issue by jonathanasdf** [huggingface/text-generation-inference#734]
I can load this in transformers using device='auto' but when I try loading in tgi even with tiny max_total_tokens and max_batch_prefill_tokens I get cuda OOM. Nothing else using GPU memory. Is this configuration possible?

loading with quantization works but I would prefer 16bit

**Comment by Narsil** [comment]
No or very barely (like very small leftovers).

`device="auto"` will offload to CPU and then the disk if I'm not mistaken so you might not see if the model actually fits.

When we tested 2A100, the leftover memory was so minimal it wasn't really worth deploying (very poor throughput because not enough VRAM to stack requests).

For 4A100 should work like a charm, 2A100 you could try the GPTQ versions by TheBloke https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ they work like a charm. (We haven't done a full ppl afaik, but results seemed reasonable)

**Comment by jonathanasdf** [comment]
Thank you

**Comment by bp020108** [comment]
can you please let me know if what is best model for GPU A100 80GB? and what would be GPU layers/batch size/chunk/tokens to maximize the performance ?
