### ISSUE TITLE
Sharding a single model across multiple nodes

### ISSUE THREAD

**Issue by jshin49** [huggingface/text-generation-inference#752]
### Feature request

Is it possible to shard a single model across multiple nodes with this? For example, 8 x 8-A100 Node.

### Motivation

If we're planning to use larger models like 175B in the future, this feature would be great to have. I'm not sure if it's already supported.

### Your contribution

Not sure

**Comment by Narsil** [comment]
Hi @jshin49 .

Currently we can support bloom 175B (https://huggingface.co/bigscience/bloom) on 1 8xA100 (80GB) node (or 16xA100(40GB)).
It might not be the optimal deployment but it works.

We currently have no plan to do multinode, because the latency hit of doing actual network seems prohibitive.
H100 might also be a good hardware solution to this problem.

Nothing is ever off the table, but we usually try to keep solving actual issues than developing something not currently in demand.

I will go ahead and close this for now, as it's definitely not in our short term roadmap, but we'll definitely revisit once there's such a need. I'm pretty sure by then it will be multimodal,mixture of experts and therefore the landscape of the solution will have changed.
