### ISSUE TITLE
Using Conversational Pipeline with TGI

### ISSUE THREAD

**Issue by HamidShojanazeri** [huggingface/text-generation-inference#796]
### Feature request

I am interested to see if TGI support conversational pipeline/ any plan to add it. 

```
chatbot = ConversationalPipeline(model=model,tokenizer = tokenizer, device = 0, max_length=435,temperature=0.6,top_p=0.9)
conversation = Conversation("What is so great about Paris ?", past_user_inputs = ["...."], generated_responses=["Paris, the capital of France, ...."])
conversation = chatbot(conversation)

```

### Motivation

This would be helpful to handle conversations easier providing the context from previous conversations.

### Your contribution

Will be interested to help with verifying the functionality/ optimizations. 

cc: @Narsil

**Comment by Narsil** [comment]
Hi not really, this repo aims to be agnostic so such things (as it's impossible to keep track of all variants).

We're working on some harmonization in HF. In the meantime you could try: https://github.com/philschmid/easyllm

**Comment by HamidShojanazeri** [comment]
Thanks @Narsil, I am thinking if easyllm, would provide similar optimizations such as flashv2, paged attention etc.

I wonder if you have any suggestion that in current TGI workflow how can we send the type of input I mentioned above, basically prompt+ context (such as few previous chats with the assistant).

**Comment by Narsil** [comment]
Hey @HamidShojanazeri .

TGI receives raw strings, it's not responsible for the chat layout (every model does it differently). TGI is responsible for flashv2 and such (check the logs to see if it' s being used).

easyllm is the simple formatter that takes a standardized prompt and applies what is required for the specified model.

I'm closing this since we' re not doing ConversationPipeline like.
