### ISSUE TITLE
Add JS example using @huggingface/inference library

### ISSUE THREAD

**Issue by osanseviero** [huggingface/text-generation-inference#873]
We can do something like this for using the API in JS

cc @merveenoyan 

`npm install @huggingface/inference`

```js
import { HfInferenceEndpoint } from '@huggingface/inference'

const hf = new HfInferenceEndpoint('https://YOUR_ENDPOINT.endpoints.huggingface.cloud', 'hf_YOUR_TOKEN')

// prompt
const prompt = 'What can you do in Nuremberg, Germany? Give me 3 Tips'

const stream = hf.textGenerationStream({ inputs: prompt })
for await (const r of stream) {
  // # skip special tokens
  if (r.token.special) {
    continue
  }
  // stop if we encounter a stop sequence
  if (gen_kwargs['stop_sequences'].includes(r.token.text)) {
    break
  }
  // yield the generated token
  process.stdout.write(r.token.text)
}```

**Comment by josephrocca** [comment]
Wondering why the JS library doesn't have a "real" `stop_sequences`? I mean so that it actually stops the inference on the server, and not just "ignores" the rest of the stream on the client.

`stop_sequences` is mentioned [here](https://github.com/huggingface/huggingface.js/blob/2a7b6837e4d5c977927736856cfe7984cec8de55/packages/inference/src/tasks/nlp/textGenerationStream.ts#L52) in `src/tasks/nlp/textGenerationStream.ts` as a `TextGenerationStreamFinishReason`, but I can't find any other references to it in the `huggingface.js` repo, and it doesn't seem to work as a parameter in my testing.

Also would `stop_sequences.includes(r.token.text)` actually work? I thought `stop_sequences` would be an array of arbitrary strings, rather than strings that exactly match a token?

**Comment by josephrocca** [comment]
Okay, so for the JS client it's called `stop` instead of `stop_sequences`. So, for example:

```bash
docker run --gpus all --shm-size 1g -p 8080:80 -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id abacaj/starcoderbase-1b-sft
```
and then:
```js
let { HfInferenceEndpoint } = await import('https://cdn.jsdelivr.net/npm/@huggingface/inference@2.6.1/+esm');
let hf = new HfInferenceEndpoint('http://localhost:8080');
let prompt = `Write a python function to sort the following array in ascending order, don't use any built in sorting methods: [9,2,8,1,5]`;
let stream = hf.textGenerationStream({
  inputs: `[Instructions]:\n${prompt}\n\n[Response]:`,
  parameters: {max_new_tokens:1000, stop:["function"]},
});
for await (const r of stream) {
  console.log(r.token.text);
}
```
That works.

I think `stop` is the "backend" name, since the Python client has `stop_sequences` and that is [converted into](https://github.com/huggingface/text-generation-inference/blob/c8a01d759173483efc2135c4e7506b23e14e7fc4/clients/python/text_generation/client.py#L132C13-L132C13) `stop` when making the actual request to the inference server.

*However*, it's not possible to put "subwords" in the `stop` array. Full words only, it seems. So using "function" as a stop sequence works, but "funct" doesn't. This is counter-intuitive, and not how other APIs work (like OpenAI) - stop sequences are usually guaranteed to not be in the output.

@merveenoyan @osanseviero wondering if you can comment on this?

**Comment by josephrocca** [comment]
Hmm, this is unrelated to the JS API, and unrelated to streaming - i.e. it's a problem for non-streaming requests too. I've added a comment asking about this here:

https://github.com/huggingface/text-generation-inference/issues/332#issuecomment-1716606747

**Comment by erfanium** [comment]
`@huggingface/inference` also is acking the `details` props.
