### ISSUE TITLE
Add some documentation on benchmarking

### ISSUE THREAD

**Issue by osanseviero** [huggingface/text-generation-inference#875]

**Comment by merveenoyan** [comment]
@aisensiy yes, you can benchmark both TGI & vLLM in TGB.

**Comment by Narsil** [comment]
@merveenoyan No you cannot.

`text-generation-benchmark`  bypasses the router in order to control everything directly at the gRPC layer which vLLM doesn' t implement.

If you want to make performance comparisons you can check https://github.com/huggingface/text-generation-inference/tree/main/load_tests which uses `k6`.

Try to make sure you are in optimal conditions for both setups when doing benchmarks. The suggested benchmark is actually not really the best. Check out https://k6.io/docs/test-types/load-test-types/ for more information on benchmarking live systems.

**Comment by merveenoyan** [comment]
@aisensiy I believe it's better if you benchmark them on same machine. What kind of info are you looking for? We are documenting this bit as well so I thought I'd add while I'm on it.

**Comment by merveenoyan** [comment]
@aisensiy I think it's better if @narsilou replies. I edited my answer accordingly. AFAIR, the feature was being added or was there.
