### ISSUE TITLE
Inconsistency in internal `do_sample` override logic

### ISSUE THREAD

**Issue by shijie-wu** [huggingface/text-generation-inference#945]
### System Info

main

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

n/a

### Expected behavior

On the rust side, `sampling` is overridden to `True` if any of the following arg is **set**.
https://github.com/huggingface/text-generation-inference/blob/5485c142e87a182f2eee713a6b056ee38bd901f5/router/src/validation.rs#L154-L158
However, on the python side, `sampling` is overridden to `True` if any of the following arg is **not set to a specific value**.
https://github.com/huggingface/text-generation-inference/blob/5485c142e87a182f2eee713a6b056ee38bd901f5/server/text_generation_server/utils/tokens.py#L42-L56
such inconsistency cause user confusion like https://github.com/huggingface/text-generation-inference/issues/687.

It might make sense to set `sampling` to `True` if any of the above arg is **set**. This can be done by replacing the following
https://github.com/huggingface/text-generation-inference/blob/5485c142e87a182f2eee713a6b056ee38bd901f5/router/src/validation.rs#L260
with `sampling`

**Comment by ollmer** [comment]
Hi! I came across a similar problem, but about the inability to make repeatable generations with `do_sample=False`.  

In my case, I can't skip setting temp and other fields in the API call, because according to [the doc](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/generate) they will have some default values that are not compatible with the greedy decoding. And I also can't pass all the correct values required [to not override do_sample](https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/utils/tokens.py#L42) (temperature=1.0, top_k=0, top_p=1.0, typical_p=1.0), because in that case, I got API validation error `received unknown error from API: Input validation error: `top_p` must be > 0.0 and < 1.0`
I do not understand what is the motivation for overriding the sampling flag with the temp, top_k, and other values. 

@Narsil (or @OlivierDehaene) could you please elaborate on why this design decision was made? Thank you in advance.

**Comment by v-prgmr** [comment]
@shijie-wu while generating text outputs using TGI, and setting `do_sample` as `false` in

`HuggingFaceTextGenInference(
            inference_server_url=inference_server_url,
            max_new_tokens=250,
            #top_k=10,
            #top_p=0.95,
            #typical_p=0.95,
            #temperature=0.01,
            repetition_penalty=1.03,
            truncate=4096,
            do_sample=False)`


does not generate deterministic outputs.
